name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 'latest'  # Usando a versão mais recente do Python

    - name: Install poetry
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry

    - name: Check poetry version
      run: poetry --version

    - name: Install dependencies
      shell: bash
      run: poetry install

    - name: Check dependencies
      run: poetry show

    - name: Run tests
      run: |
        poetry run python manage.py test --verbosity=2
